package io.openlist.client.core.database

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v0.1.0 has shipped with real user data, so schema changes from here on are
 * hand-written Migrations registered in `di/DatabaseModule`, never a
 * destructive fallback (v0.2_EXECUTION_PLAN.md B3/P4).
 */

/** Adds the `/api/me` permission bitmask so write-permission gating (Sprint 3)
 * has a user-level fallback alongside the directory-level `FsListResp.write`. */
val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE sessions ADD COLUMN permission INTEGER NOT NULL DEFAULT 0")
    }
}

/** Adds `upload_tasks` (Sprint 6). Column order/types mirror UploadTaskEntity
 * exactly — cross-checked against Room's own generated createSql for the
 * other task tables in the exported schema JSON files, rather than guessed. */
val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `upload_tasks` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`targetDir` TEXT NOT NULL, " +
                "`localUri` TEXT NOT NULL, " +
                "`fileName` TEXT NOT NULL, " +
                "`mimeType` TEXT, " +
                "`totalBytes` INTEGER, " +
                "`uploadedBytes` INTEGER NOT NULL, " +
                "`status` TEXT NOT NULL, " +
                "`errorMessage` TEXT, " +
                "`workRequestId` TEXT, " +
                "`overwrite` INTEGER NOT NULL, " +
                "`createdAt` INTEGER NOT NULL, " +
                "`updatedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`))",
        )
    }
}

/** Adds `shares`, `search_history`, `remote_tasks` (v0.3 Sprint 0, S0-T2).
 * Column order/types generated by first bumping `OpenListDatabase` to
 * version 7 and reading Room's own exported schema
 * (`core/database/schemas/.../7.json`), then copied verbatim here — same
 * cross-check discipline as MIGRATION_5_6, never guessed. */
val MIGRATION_6_7 = object : Migration(6, 7) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `shares` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`filesJson` TEXT NOT NULL, " +
                "`primaryPath` TEXT NOT NULL, " +
                "`name` TEXT, " +
                "`shareUrl` TEXT, " +
                "`password` TEXT, " +
                "`enabled` INTEGER NOT NULL, " +
                "`expiresAt` INTEGER, " +
                "`accessed` INTEGER NOT NULL, " +
                "`maxAccessed` INTEGER NOT NULL, " +
                "`creator` TEXT, " +
                "`rawJson` TEXT NOT NULL, " +
                "`createdAt` INTEGER, " +
                "`updatedAt` INTEGER, " +
                "`cachedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`, `instanceId`))",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `search_history` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`keyword` TEXT NOT NULL, " +
                "`scopePath` TEXT, " +
                "`searchedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`))",
        )
        db.execSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS `index_search_history_instanceId_keyword_scopePath` " +
                "ON `search_history` (`instanceId`, `keyword`, `scopePath`)",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `remote_tasks` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`taskType` TEXT NOT NULL, " +
                "`title` TEXT NOT NULL, " +
                "`stateRaw` INTEGER NOT NULL, " +
                "`status` TEXT NOT NULL, " +
                "`progress` INTEGER, " +
                "`targetPath` TEXT, " +
                "`errorMessage` TEXT, " +
                "`totalBytes` INTEGER, " +
                "`rawJson` TEXT NOT NULL, " +
                "`startTime` INTEGER, " +
                "`endTime` INTEGER, " +
                "`cachedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`, `instanceId`))",
        )
    }
}

/**
 * Adds `preview_cache` (v0.4 Sprint 1, S1-T2, P-415). Column order/types
 * hand-derived from `PreviewCacheEntity` and cross-checked field-by-field
 * against the hand-written `8.json` schema export added alongside this
 * migration — same cross-check discipline as MIGRATION_5_6/MIGRATION_6_7,
 * but **unlike** those two, this one could not be verified by actually
 * running Room's KSP schema export (no build environment available in this
 * sprint): it is a manual derivation from the Kotlin -> SQLite type mapping
 * used elsewhere in this file (String -> TEXT, Long -> INTEGER, nullable
 * Kotlin types omit `NOT NULL`). Re-verify against a real KSP-exported
 * schema the next time this module is built.
 */
val MIGRATION_7_8 = object : Migration(7, 8) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `preview_cache` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`path` TEXT NOT NULL, " +
                "`kind` TEXT NOT NULL, " +
                "`mimeType` TEXT, " +
                "`lastModified` INTEGER, " +
                "`cacheKey` TEXT NOT NULL, " +
                "`localFilePath` TEXT NOT NULL, " +
                "`sizeBytes` INTEGER NOT NULL, " +
                "`etag` TEXT, " +
                "`expiresAt` INTEGER, " +
                "`cachedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`))",
        )
        db.execSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS `index_preview_cache_instanceId_path_kind` " +
                "ON `preview_cache` (`instanceId`, `path`, `kind`)",
        )
    }
}

/**
 * Adds `admin_cache` (v0.5 Sprint 1, S1-T6, PRD §11.6). Column order/types
 * hand-derived from `AdminCacheEntity` and cross-checked field-by-field
 * against the hand-written `9.json` schema export added alongside this
 * migration — same cross-check discipline as MIGRATION_5_6/MIGRATION_6_7/
 * MIGRATION_7_8. Like MIGRATION_7_8, this could not be verified by actually
 * running Room's KSP schema export in this sprint's environment: it is a
 * manual derivation from the same Kotlin -> SQLite type mapping used
 * elsewhere in this file (String -> TEXT, Long -> INTEGER, nullable Kotlin
 * types omit `NOT NULL`). Re-verify against a real KSP-exported schema the
 * next time this module is built in a full Android build environment
 * (inherits the same caveat already on record for 8.json — see KNOWN_ISSUES).
 */
val MIGRATION_8_9 = object : Migration(8, 9) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `admin_cache` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`scope` TEXT NOT NULL, " +
                "`cacheKey` TEXT NOT NULL, " +
                "`rawJson` TEXT NOT NULL, " +
                "`cachedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`))",
        )
        db.execSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS `index_admin_cache_instanceId_scope_cacheKey` " +
                "ON `admin_cache` (`instanceId`, `scope`, `cacheKey`)",
        )
    }
}

/**
 * Adds `recent_paths` for the v1.1 home workspace. This is the only v1.1
 * schema change and deliberately does not alter any existing table.
 */
val MIGRATION_9_10 = object : Migration(9, 10) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `recent_paths` (" +
                "`instanceId` TEXT NOT NULL, " +
                "`path` TEXT NOT NULL, " +
                "`displayName` TEXT NOT NULL, " +
                "`visitedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`instanceId`, `path`))",
        )
        db.execSQL(
            "CREATE INDEX IF NOT EXISTS `index_recent_paths_instanceId_visitedAt` " +
                "ON `recent_paths` (`instanceId`, `visitedAt`)",
        )
    }
}

/**
 * v1.4 DocumentsProvider mapping and write journal. This migration only adds
 * tables and indices; existing instance/session/cache/task data is untouched.
 */
val MIGRATION_10_11 = object : Migration(10, 11) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `system_documents` (" +
                "`documentId` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`parentDocumentId` TEXT, " +
                "`currentPath` TEXT, " +
                "`lastKnownPath` TEXT NOT NULL, " +
                "`displayName` TEXT NOT NULL, " +
                "`isDirectory` INTEGER NOT NULL, " +
                "`mimeType` TEXT NOT NULL, " +
                "`sizeBytes` INTEGER, " +
                "`modifiedAt` INTEGER, " +
                "`hashInfo` TEXT, " +
                "`provider` TEXT, " +
                "`lifecycle` TEXT NOT NULL, " +
                "`unsupportedCapabilitiesMask` INTEGER NOT NULL, " +
                "`capabilityUpdatedAt` INTEGER, " +
                "`lastSeenAt` INTEGER NOT NULL, " +
                "`updatedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`documentId`))",
        )
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_system_documents_instanceId_currentPath` ON `system_documents` (`instanceId`, `currentPath`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_system_documents_instanceId_parentDocumentId_lifecycle` ON `system_documents` (`instanceId`, `parentDocumentId`, `lifecycle`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_system_documents_instanceId_lastKnownPath` ON `system_documents` (`instanceId`, `lastKnownPath`)")
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `system_write_transactions` (" +
                "`transactionId` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`documentId` TEXT, " +
                "`targetPath` TEXT NOT NULL, " +
                "`displayName` TEXT NOT NULL, " +
                "`localRelativePath` TEXT NOT NULL, " +
                "`remoteTempPath` TEXT, " +
                "`remoteBackupPath` TEXT, " +
                "`remoteStageName` TEXT, " +
                "`remoteBackupName` TEXT, " +
                "`state` TEXT NOT NULL, " +
                "`dirtyGeneration` INTEGER NOT NULL, " +
                "`committedGeneration` INTEGER NOT NULL, " +
                "`reservedBytes` INTEGER NOT NULL, " +
                "`expectedSize` INTEGER, " +
                "`expectedHash` TEXT, " +
                "`baseFingerprint` TEXT, " +
                "`failureStage` TEXT, " +
                "`errorCode` TEXT, " +
                "`errorMessage` TEXT, " +
                "`attemptCount` INTEGER NOT NULL, " +
                "`lastAttemptAt` INTEGER, " +
                "`cleanupAfter` INTEGER, " +
                "`expiresAt` INTEGER, " +
                "`createdAt` INTEGER NOT NULL, " +
                "`updatedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`transactionId`))",
        )
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_system_write_transactions_instanceId_state_updatedAt` ON `system_write_transactions` (`instanceId`, `state`, `updatedAt`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_system_write_transactions_instanceId_documentId_state` ON `system_write_transactions` (`instanceId`, `documentId`, `state`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_system_write_transactions_expiresAt_state` ON `system_write_transactions` (`expiresAt`, `state`)")
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_system_write_transactions_localRelativePath` ON `system_write_transactions` (`localRelativePath`)")
    }
}
