package io.openlist.client.core.database

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v0.1.0 has shipped with real user data, so schema changes from here on are
 * hand-written Migrations registered in `di/DatabaseModule`, never a
 * destructive fallback (v0.2_EXECUTION_PLAN.md B3/P4).
 */

/** Adds the `/api/me` permission bitmask so write-permission gating (Sprint 3)
 * has a user-level fallback alongside the directory-level `FsListResp.write`. */
val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("ALTER TABLE sessions ADD COLUMN permission INTEGER NOT NULL DEFAULT 0")
    }
}

/** Adds `upload_tasks` (Sprint 6). Column order/types mirror UploadTaskEntity
 * exactly — cross-checked against Room's own generated createSql for the
 * other task tables in the exported schema JSON files, rather than guessed. */
val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `upload_tasks` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`targetDir` TEXT NOT NULL, " +
                "`localUri` TEXT NOT NULL, " +
                "`fileName` TEXT NOT NULL, " +
                "`mimeType` TEXT, " +
                "`totalBytes` INTEGER, " +
                "`uploadedBytes` INTEGER NOT NULL, " +
                "`status` TEXT NOT NULL, " +
                "`errorMessage` TEXT, " +
                "`workRequestId` TEXT, " +
                "`overwrite` INTEGER NOT NULL, " +
                "`createdAt` INTEGER NOT NULL, " +
                "`updatedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`))",
        )
    }
}

/** Adds `shares`, `search_history`, `remote_tasks` (v0.3 Sprint 0, S0-T2).
 * Column order/types generated by first bumping `OpenListDatabase` to
 * version 7 and reading Room's own exported schema
 * (`core/database/schemas/.../7.json`), then copied verbatim here — same
 * cross-check discipline as MIGRATION_5_6, never guessed. */
val MIGRATION_6_7 = object : Migration(6, 7) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `shares` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`filesJson` TEXT NOT NULL, " +
                "`primaryPath` TEXT NOT NULL, " +
                "`name` TEXT, " +
                "`shareUrl` TEXT, " +
                "`password` TEXT, " +
                "`enabled` INTEGER NOT NULL, " +
                "`expiresAt` INTEGER, " +
                "`accessed` INTEGER NOT NULL, " +
                "`maxAccessed` INTEGER NOT NULL, " +
                "`creator` TEXT, " +
                "`rawJson` TEXT NOT NULL, " +
                "`createdAt` INTEGER, " +
                "`updatedAt` INTEGER, " +
                "`cachedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`, `instanceId`))",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `search_history` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`keyword` TEXT NOT NULL, " +
                "`scopePath` TEXT, " +
                "`searchedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`))",
        )
        db.execSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS `index_search_history_instanceId_keyword_scopePath` " +
                "ON `search_history` (`instanceId`, `keyword`, `scopePath`)",
        )
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `remote_tasks` (" +
                "`id` TEXT NOT NULL, " +
                "`instanceId` TEXT NOT NULL, " +
                "`taskType` TEXT NOT NULL, " +
                "`title` TEXT NOT NULL, " +
                "`stateRaw` INTEGER NOT NULL, " +
                "`status` TEXT NOT NULL, " +
                "`progress` INTEGER, " +
                "`targetPath` TEXT, " +
                "`errorMessage` TEXT, " +
                "`totalBytes` INTEGER, " +
                "`rawJson` TEXT NOT NULL, " +
                "`startTime` INTEGER, " +
                "`endTime` INTEGER, " +
                "`cachedAt` INTEGER NOT NULL, " +
                "PRIMARY KEY(`id`, `instanceId`))",
        )
    }
}
